#!/bin/bash
vol="$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{printf "%d", $2 * 100}')"
muted="$(wpctl get-volume @DEFAULT_AUDIO_SINK@)"
if [[ "$muted" == *"[MUTED]"* ]]; then
    echo "^c#ff71ce^🔇 ${vol}% "
else
    echo "^c#ff71ce^🔊 ${vol}% "
fi
